language: node_js

node_js:
   - "10"

branches:
  only:
    - master
    - develop

install:
  - npm install

matrix:
  include:
    - name: "Js Browser"
      env: PACKAGE=packages/js-browser
    - name: "Js Logger"
      env: PACKAGE=packages/js-logger
    - name: "Js EventBus"
      env: PACKAGE=packages/js-eventbus

script: .travis/build_package.sh
#script:
#  - cd $PACKAGE_LOCATION
