language: node_js

node_js:
   - "10"

branches:
  only:
    - master
    - develop

install:
  - npm install

matrix:
  include:
    - name: "Js Browser"
      env: PACKAGE=packages/js-browser
    - name: "Js Logger"
      env: PACKAGE=packages/js-logger
    - name: "Js EventBus"
      env: PACKAGE=packages/js-eventbus

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then echo "$PROJECT is being built"; else echo "$PROJECT is NOT being built"; fi

#script:
#  - cd $PACKAGE_LOCATION
